---
name: MCVS-PR-validation-action
"on":
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_call:
permissions:
  contents: read
  pull-requests: read
jobs:
  MCVS-PR-validation-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: schubergphilis/mcvs-pr-validation-action@12587186ddd0cf2a2acd20495f3b31262af1f610 # v0.2.1
